//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub r#type: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub search: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub hash: String,
    pub width: Option<i32>,
    pub height: Option<i32>,
    pub size: Option<i32>,
    pub timestamp:i64,
    pub tag_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
